# # -*- coding: utf-8 -*-
# """
#
# """
#
# __all__ = ["CtrlKL"]
#
# import logging
#
# from .utils import CLILog
# from .opc_connect import ConnectOPC
#
#
# class CtrlKL(ConnectOPC):
#
#     def __init__(self):
#         super().__init__()
#         # print(__name__)
#         self.dic_relay = {'KL1': 'Устройство.tg.in_perekl_rejimov_KL1',
#                           'KL2': 'Устройство.tg.in_power_18V_KL2',
#                           'KL3': 'Устройство.tg.in_R1_KL3',
#                           'KL4': 'Устройство.tg.in_R2_KL4',
#                           'KL5': 'Устройство.tg.in_R3_KL5',
#                           'KL6': 'Устройство.tg.in_R4_KL6',
#                           'KL7': 'Устройство.tg.in_R5_KL7',
#                           'KL8': 'Устройство.tg.in_R6_KL8',
#                           'KL9': 'Устройство.tg.in_R7_KL9',
#                           'KL10': 'Устройство.tg.in_R8_KL10',
#                           'KL11': 'Устройство.tg.in_KZ_KL11',
#                           'KL12': 'Устройство.tg.in_pusk_KL12',
#                           'KL13': 'Устройство.tg.in_R10_KL13',
#                           'KL14': 'Устройство.tg.in_R11_KL14',
#                           'KL15': 'Устройство.tg.in_R12_KL15',
#                           'KL16': 'Устройство.tg.in_R13_KL16',
#                           'KL17': 'Устройство.tg.in_R14_KL17',
#                           'KL18': 'Устройство.tg.in_R15_KL18',
#                           'KL19': 'Устройство.tg.in_R16_KL19',
#                           'KL20': 'Устройство.tg.in_R17_KL20',
#                           'KL21': 'Устройство.tg.in_power_36V_KL21',
#                           'KL22': 'Устройство.tg.in_perekl_KI_BKI_KL22',
#                           'KL23': 'Устройство.tg.in_perekl_660V_1140V_KL23',
#                           'KL24': 'Устройство.tg.in_shunt_D_KL24',
#                           'KL25': 'Устройство.tg.in_R_shunt_KL25',
#                           'KL26': 'Устройство.tg.in_DU_KL26',
#                           'KL27': 'Устройство.tg.in_cont_ser_KT_KL27',
#                           'KL28': 'Устройство.tg.in_perek_18V_KL28',
#                           'KL29': 'Устройство.tg.in_KL29',
#                           'KL30': 'Устройство.tg.in_power_KT_KL30',
#                           'KL31': 'Устройство.tg.in_perekl_kanalov_KL31',
#                           'KL32': 'Устройство.tg.in_power_110V_KL32',
#                           'KL33': 'Устройство.tg.in_power_15V_KL33',
#                           'KL36': 'Устройство.tg.in_power_48V_KL36',
#                           'KL37': 'Устройство.tg.in_puskovoi_R_KL37',
#                           'KL38': 'Устройство.tg.in_perv_obm_TV1_KL38',
#                           'KL39': 'Устройство.tg.in_perv_obm_TV1_KL39',
#                           'KL40': 'Устройство.tg.in_perv_obm_TV1_KL40',
#                           'KL41': 'Устройство.tg.in_perv_obm_TV1_KL41',
#                           'KL42': 'Устройство.tg.in_perv_obm_TV1_KL42',
#                           'KL43': 'Устройство.tg.in_perv_obm_TV1_KL43',
#                           'KL44': 'Устройство.tg.in_perv_obm_TV1_KL44',
#                           'KL45': 'Устройство.tg.in_perv_obm_TV1_KL45',
#                           'KL46': 'Устройство.tg.in_perv_obm_TV1_KL46',
#                           'KL47': 'Устройство.tg.in_perv_obm_TV1_KL47',
#                           'KL48': 'Устройство.tg.in_vtor_obm_TV1_KL48',
#                           'KL49': 'Устройство.tg.in_vtor_obm_TV1_KL49',
#                           'KL50': 'Устройство.tg.in_vtor_obm_TV1_KL50',
#                           'KL51': 'Устройство.tg.in_vtor_obm_TV1_KL51',
#                           'KL52': 'Устройство.tg.in_vtor_obm_TV1_KL52',
#                           'KL53': 'Устройство.tg.in_vtor_obm_TV1_KL53',
#                           'KL54': 'Устройство.tg.in_vtor_obm_TV1_KL54',
#                           'KL55': 'Устройство.tg.in_vtor_obm_TV1_KL55',
#                           'KL56': 'Устройство.tg.in_vtor_obm_TV1_KL56',
#                           'KL57': 'Устройство.tg.in_vtor_obm_TV1_KL57',
#                           'KL58': 'Устройство.tg.in_vtor_obm_TV1_KL58',
#                           'KL59': 'Устройство.tg.in_vtor_obm_TV1_KL59',
#                           'KL60': 'Устройство.tg.in_KZ_obmotka_KL60',
#                           'KL62': 'Устройство.tg.in_perv_gl_kont_KL62',
#                           'KL63': 'Устройство.tg.in_vtor_gl_kont_KL63',
#                           'KL65': 'Устройство.tg.in_KL65',
#                           'KL66': 'Устройство.tg.in_power_12V_KL66',
#                           'KL67': 'Устройство.tg.in_KL67',
#                           'KL68': 'Устройство.tg.in_KL68',
#                           'KL69': 'Устройство.tg.in_KL69',
#                           'KL70': 'Устройство.tg.in_KL88',
#                           'KL71': 'Устройство.tg.in_KL71',
#                           'KL72': 'Устройство.tg.in_KL72',
#                           'KL73': 'Устройство.tg.in_rejim_AB_VG_KL73',
#                           'KL74': 'Устройство.tg.in_rejim_rabor_KL74',
#                           'KL75': 'Устройство.tg.in_KL75',
#                           'KL76': 'Устройство.tg.in_KL76',
#                           'KL77': 'Устройство.tg.in_KL77',
#                           'KL78': 'Устройство.tg.in_KL78',
#                           'KL79': 'Устройство.tg.in_KL79',
#                           'KL80': 'Устройство.tg.in_KL80',
#                           'KL81': 'Устройство.tg.in_KL81',
#                           'KL82': 'Устройство.tg.in_KL82',
#                           'KL83': 'Устройство.tg.in_KL83',
#                           'KL84': 'Устройство.tg.in_KL84',
#                           'KL88': 'Устройство.tg.in_KL88',
#                           'KL89': 'Устройство.tg.in_KL89',
#                           'KL90': 'Устройство.tg.in_KL90',
#                           'KL91': 'Устройство.tg.in_KL91',
#                           'KL92': 'Устройство.tg.in_KL92',
#                           'KL93': 'Устройство.tg.in_KL93',
#                           'KL94': 'Устройство.tg.in_KL94',
#                           'KL95': 'Устройство.tg.in_KL95',
#                           'KL97': 'Устройство.tg.in_KL97',
#                           'KL98': 'Устройство.tg.in_KL98',
#                           'KL99': 'Устройство.tg.in_KL99',
#                           'KL100': 'Устройство.tg.in_KL100',
#                           'Q113_4': 'Устройство.tg.in_Q113_4',
#                           'Q113_5': 'Устройство.tg.in_Q113_5',
#                           'Q113_6': 'Устройство.tg.in_Q113_6',
#                           'Q113_7': 'Устройство.tg.in_Q113_7'}
#         self.list_relay = ('Устройство.tg.in_perekl_rejimov_KL1', 'Устройство.tg.in_power_18V_KL2',
#                            'Устройство.tg.in_R1_KL3', 'Устройство.tg.in_R2_KL4',
#                            'Устройство.tg.in_R3_KL5', 'Устройство.tg.in_R4_KL6',
#                            'Устройство.tg.in_R5_KL7', 'Устройство.tg.in_R6_KL8',
#                            'Устройство.tg.in_R7_KL9', 'Устройство.tg.in_R8_KL10',
#                            'Устройство.tg.in_KZ_KL11', 'Устройство.tg.in_pusk_KL12',
#                            'Устройство.tg.in_R10_KL13', 'Устройство.tg.in_R11_KL14',
#                            'Устройство.tg.in_R12_KL15', 'Устройство.tg.in_R13_KL16',
#                            'Устройство.tg.in_R14_KL17', 'Устройство.tg.in_R15_KL18',
#                            'Устройство.tg.in_R16_KL19', 'Устройство.tg.in_R17_KL20',
#                            'Устройство.tg.in_power_36V_KL21', 'Устройство.tg.in_perekl_KI_BKI_KL22',
#                            'Устройство.tg.in_perekl_660V_1140V_KL23', 'Устройство.tg.in_shunt_D_KL24',
#                            'Устройство.tg.in_R_shunt_KL25', 'Устройство.tg.in_DU_KL26',
#                            'Устройство.tg.in_cont_ser_KT_KL27', 'Устройство.tg.in_perek_18V_KL28',
#                            'Устройство.tg.in_KL29', 'Устройство.tg.in_power_KT_KL30',
#                            'Устройство.tg.in_perekl_kanalov_KL31', 'Устройство.tg.in_power_110V_KL32',
#                            'Устройство.tg.in_power_15V_KL33', 'Устройство.tg.in_power_48V_KL36',
#                            'Устройство.tg.in_puskovoi_R_KL37', 'Устройство.tg.in_perv_obm_TV1_KL38',
#                            'Устройство.tg.in_perv_obm_TV1_KL39', 'Устройство.tg.in_perv_obm_TV1_KL40',
#                            'Устройство.tg.in_perv_obm_TV1_KL41', 'Устройство.tg.in_perv_obm_TV1_KL42',
#                            'Устройство.tg.in_perv_obm_TV1_KL43', 'Устройство.tg.in_perv_obm_TV1_KL44',
#                            'Устройство.tg.in_perv_obm_TV1_KL45', 'Устройство.tg.in_perv_obm_TV1_KL46',
#                            'Устройство.tg.in_perv_obm_TV1_KL47', 'Устройство.tg.in_vtor_obm_TV1_KL48',
#                            'Устройство.tg.in_vtor_obm_TV1_KL49', 'Устройство.tg.in_vtor_obm_TV1_KL50',
#                            'Устройство.tg.in_vtor_obm_TV1_KL51', 'Устройство.tg.in_vtor_obm_TV1_KL52',
#                            'Устройство.tg.in_vtor_obm_TV1_KL53', 'Устройство.tg.in_vtor_obm_TV1_KL54',
#                            'Устройство.tg.in_vtor_obm_TV1_KL55', 'Устройство.tg.in_vtor_obm_TV1_KL56',
#                            'Устройство.tg.in_vtor_obm_TV1_KL57', 'Устройство.tg.in_vtor_obm_TV1_KL58',
#                            'Устройство.tg.in_vtor_obm_TV1_KL59', 'Устройство.tg.in_KZ_obmotka_KL60',
#                            'Устройство.tg.in_perv_gl_kont_KL62', 'Устройство.tg.in_vtor_gl_kont_KL63',
#                            'Устройство.tg.in_KL65', 'Устройство.tg.in_power_12V_KL66',
#                            'Устройство.tg.in_KL67', 'Устройство.tg.in_KL68',
#                            'Устройство.tg.in_KL69', 'Устройство.tg.in_KL88',
#                            'Устройство.tg.in_KL71', 'Устройство.tg.in_KL72',
#                            'Устройство.tg.in_rejim_AB_VG_KL73', 'Устройство.tg.in_rejim_rabor_KL74',
#                            'Устройство.tg.in_KL75', 'Устройство.tg.in_KL76',
#                            'Устройство.tg.in_KL77', 'Устройство.tg.in_KL78',
#                            'Устройство.tg.in_KL79', 'Устройство.tg.in_KL80',
#                            'Устройство.tg.in_KL81', 'Устройство.tg.in_KL82',
#                            'Устройство.tg.in_KL83', 'Устройство.tg.in_KL84',
#                            'Устройство.tg.in_KL88', 'Устройство.tg.in_KL89',
#                            'Устройство.tg.in_KL90', 'Устройство.tg.in_KL91',
#                            'Устройство.tg.in_KL92', 'Устройство.tg.in_KL93',
#                            'Устройство.tg.in_KL94', 'Устройство.tg.in_KL95',
#                            'Устройство.tg.in_KL97', 'Устройство.tg.in_KL98',
#                            'Устройство.tg.in_KL99', 'Устройство.tg.in_KL100',
#                            'Устройство.tg.in_Q113_4', 'Устройство.tg.in_Q113_5',
#                            'Устройство.tg.in_Q113_6', 'Устройство.tg.in_Q113_7')
#         self.list_relay_true = (('Устройство.tg.in_perekl_rejimov_KL1', True),
#                                 ('Устройство.tg.in_power_18V_KL2', True),
#                                 ('Устройство.tg.in_R1_KL3', True),
#                                 ('Устройство.tg.in_R2_KL4', True),
#                                 ('Устройство.tg.in_R3_KL5', True),
#                                 ('Устройство.tg.in_R4_KL6', True),
#                                 ('Устройство.tg.in_R5_KL7', True),
#                                 ('Устройство.tg.in_R6_KL8', True),
#                                 ('Устройство.tg.in_R7_KL9', True),
#                                 ('Устройство.tg.in_R8_KL10', True),
#                                 ('Устройство.tg.in_KZ_KL11', True),
#                                 ('Устройство.tg.in_pusk_KL12', True),
#                                 ('Устройство.tg.in_R10_KL13', True),
#                                 ('Устройство.tg.in_R11_KL14', True),
#                                 ('Устройство.tg.in_R12_KL15', True),
#                                 ('Устройство.tg.in_R13_KL16', True),
#                                 ('Устройство.tg.in_R14_KL17', True),
#                                 ('Устройство.tg.in_R15_KL18', True),
#                                 ('Устройство.tg.in_R16_KL19', True),
#                                 ('Устройство.tg.in_R17_KL20', True),
#                                 ('Устройство.tg.in_power_36V_KL21', True),
#                                 ('Устройство.tg.in_perekl_KI_BKI_KL22', True),
#                                 ('Устройство.tg.in_perekl_660V_1140V_KL23', True),
#                                 ('Устройство.tg.in_shunt_D_KL24', True),
#                                 ('Устройство.tg.in_R_shunt_KL25', True),
#                                 ('Устройство.tg.in_DU_KL26', True),
#                                 ('Устройство.tg.in_cont_ser_KT_KL27', True),
#                                 ('Устройство.tg.in_perek_18V_KL28', True),
#                                 ('Устройство.tg.in_KL29', True),
#                                 ('Устройство.tg.in_power_KT_KL30', True),
#                                 ('Устройство.tg.in_perekl_kanalov_KL31', True),
#                                 ('Устройство.tg.in_power_110V_KL32', True),
#                                 ('Устройство.tg.in_power_15V_KL33', True),
#                                 ('Устройство.tg.in_power_48V_KL36', True),
#                                 ('Устройство.tg.in_puskovoi_R_KL37', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL38', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL39', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL40', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL41', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL42', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL43', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL44', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL45', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL46', True),
#                                 ('Устройство.tg.in_perv_obm_TV1_KL47', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL48', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL49', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL50', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL51', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL52', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL53', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL54', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL55', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL56', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL57', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL58', True),
#                                 ('Устройство.tg.in_vtor_obm_TV1_KL59', True),
#                                 ('Устройство.tg.in_KZ_obmotka_KL60', True),
#                                 ('Устройство.tg.in_perv_gl_kont_KL62', True),
#                                 ('Устройство.tg.in_vtor_gl_kont_KL63', True),
#                                 ('Устройство.tg.in_KL65', True),
#                                 ('Устройство.tg.in_power_12V_KL66', True),
#                                 ('Устройство.tg.in_KL67', True),
#                                 ('Устройство.tg.in_KL68', True),
#                                 ('Устройство.tg.in_KL69', True),
#                                 ('Устройство.tg.in_KL88', True),
#                                 ('Устройство.tg.in_KL71', True),
#                                 ('Устройство.tg.in_KL72', True),
#                                 ('Устройство.tg.in_rejim_AB_VG_KL73', True),
#                                 ('Устройство.tg.in_rejim_rabor_KL74', True),
#                                 ('Устройство.tg.in_KL75', True),
#                                 ('Устройство.tg.in_KL76', True),
#                                 ('Устройство.tg.in_KL77', True),
#                                 ('Устройство.tg.in_KL78', True),
#                                 ('Устройство.tg.in_KL79', True),
#                                 ('Устройство.tg.in_KL80', True),
#                                 ('Устройство.tg.in_KL81', True),
#                                 ('Устройство.tg.in_KL82', True),
#                                 ('Устройство.tg.in_KL83', True),
#                                 ('Устройство.tg.in_KL84', True),
#                                 ('Устройство.tg.in_KL88', True),
#                                 ('Устройство.tg.in_KL89', True),
#                                 ('Устройство.tg.in_KL90', True),
#                                 ('Устройство.tg.in_KL91', True),
#                                 ('Устройство.tg.in_KL92', True),
#                                 ('Устройство.tg.in_KL93', True),
#                                 ('Устройство.tg.in_KL94', True),
#                                 ('Устройство.tg.in_KL95', True),
#                                 ('Устройство.tg.in_KL97', True),
#                                 ('Устройство.tg.in_KL98', True),
#                                 ('Устройство.tg.in_KL99', True),
#                                 ('Устройство.tg.in_KL100', True),
#                                 ('Устройство.tg.in_Q113_4', True),
#                                 ('Устройство.tg.in_Q113_5', True),
#                                 ('Устройство.tg.in_Q113_6', True),
#                                 ('Устройство.tg.in_Q113_7', True))
#         self.list_relay_false = (('Устройство.tg.in_perekl_rejimov_KL1', False),
#                                  ('Устройство.tg.in_power_18V_KL2', False),
#                                  ('Устройство.tg.in_R1_KL3', False),
#                                  ('Устройство.tg.in_R2_KL4', False),
#                                  ('Устройство.tg.in_R3_KL5', False),
#                                  ('Устройство.tg.in_R4_KL6', False),
#                                  ('Устройство.tg.in_R5_KL7', False),
#                                  ('Устройство.tg.in_R6_KL8', False),
#                                  ('Устройство.tg.in_R7_KL9', False),
#                                  ('Устройство.tg.in_R8_KL10', False),
#                                  ('Устройство.tg.in_KZ_KL11', False),
#                                  ('Устройство.tg.in_pusk_KL12', False),
#                                  ('Устройство.tg.in_R10_KL13', False),
#                                  ('Устройство.tg.in_R11_KL14', False),
#                                  ('Устройство.tg.in_R12_KL15', False),
#                                  ('Устройство.tg.in_R13_KL16', False),
#                                  ('Устройство.tg.in_R14_KL17', False),
#                                  ('Устройство.tg.in_R15_KL18', False),
#                                  ('Устройство.tg.in_R16_KL19', False),
#                                  ('Устройство.tg.in_R17_KL20', False),
#                                  ('Устройство.tg.in_power_36V_KL21', False),
#                                  ('Устройство.tg.in_perekl_KI_BKI_KL22', False),
#                                  ('Устройство.tg.in_perekl_660V_1140V_KL23', False),
#                                  ('Устройство.tg.in_shunt_D_KL24', False),
#                                  ('Устройство.tg.in_R_shunt_KL25', False),
#                                  ('Устройство.tg.in_DU_KL26', False),
#                                  ('Устройство.tg.in_cont_ser_KT_KL27', False),
#                                  ('Устройство.tg.in_perek_18V_KL28', False),
#                                  ('Устройство.tg.in_KL29', False),
#                                  ('Устройство.tg.in_power_KT_KL30', False),
#                                  ('Устройство.tg.in_perekl_kanalov_KL31', False),
#                                  ('Устройство.tg.in_power_110V_KL32', False),
#                                  ('Устройство.tg.in_power_15V_KL33', False),
#                                  ('Устройство.tg.in_power_48V_KL36', False),
#                                  ('Устройство.tg.in_puskovoi_R_KL37', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL38', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL39', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL40', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL41', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL42', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL43', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL44', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL45', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL46', False),
#                                  ('Устройство.tg.in_perv_obm_TV1_KL47', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL48', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL49', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL50', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL51', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL52', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL53', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL54', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL55', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL56', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL57', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL58', False),
#                                  ('Устройство.tg.in_vtor_obm_TV1_KL59', False),
#                                  ('Устройство.tg.in_KZ_obmotka_KL60', False),
#                                  ('Устройство.tg.in_perv_gl_kont_KL62', False),
#                                  ('Устройство.tg.in_vtor_gl_kont_KL63', False),
#                                  ('Устройство.tg.in_KL65', False),
#                                  ('Устройство.tg.in_power_12V_KL66', False),
#                                  ('Устройство.tg.in_KL67', False),
#                                  ('Устройство.tg.in_KL68', False),
#                                  ('Устройство.tg.in_KL69', False),
#                                  ('Устройство.tg.in_KL88', False),
#                                  ('Устройство.tg.in_KL71', False),
#                                  ('Устройство.tg.in_KL72', False),
#                                  ('Устройство.tg.in_rejim_AB_VG_KL73', False),
#                                  ('Устройство.tg.in_rejim_rabor_KL74', False),
#                                  ('Устройство.tg.in_KL75', False),
#                                  ('Устройство.tg.in_KL76', False),
#                                  ('Устройство.tg.in_KL77', False),
#                                  ('Устройство.tg.in_KL78', False),
#                                  ('Устройство.tg.in_KL79', False),
#                                  ('Устройство.tg.in_KL80', False),
#                                  ('Устройство.tg.in_KL81', False),
#                                  ('Устройство.tg.in_KL82', False),
#                                  ('Устройство.tg.in_KL83', False),
#                                  ('Устройство.tg.in_KL84', False),
#                                  ('Устройство.tg.in_KL88', False),
#                                  ('Устройство.tg.in_KL89', False),
#                                  ('Устройство.tg.in_KL90', False),
#                                  ('Устройство.tg.in_KL91', False),
#                                  ('Устройство.tg.in_KL92', False),
#                                  ('Устройство.tg.in_KL93', False),
#                                  ('Устройство.tg.in_KL94', False),
#                                  ('Устройство.tg.in_KL95', False),
#                                  ('Устройство.tg.in_KL97', False),
#                                  ('Устройство.tg.in_KL98', False),
#                                  ('Устройство.tg.in_KL99', False),
#                                  ('Устройство.tg.in_KL100', False),
#                                  ('Устройство.tg.in_Q113_4', False),
#                                  ('Устройство.tg.in_Q113_5', False),
#                                  ('Устройство.tg.in_Q113_6', False),
#                                  ('Устройство.tg.in_Q113_7', False))
#         self.list_perv_obm_tv1_off = (('Устройство.tg.in_perv_obm_TV1_KL38', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL39', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL40', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL41', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL42', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL43', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL44', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL45', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL46', False),
#                                       ('Устройство.tg.in_perv_obm_TV1_KL47', False))
#         self.list_vtor_obm_tv_off = (('Устройство.tg.in_vtor_obm_TV1_KL48', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL49', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL50', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL51', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL52', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL53', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL54', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL55', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL56', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL57', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL58', False),
#                                      ('Устройство.tg.in_vtor_obm_TV1_KL59', False),
#                                      ('Устройство.tg.in_KZ_obmotka_KL60', False))
#         self.logger = logging.getLogger(__name__)
#         self.cli_log = CLILog("info", __name__)
#         # self.logger.addHandler(logging.StreamHandler(self.logger.setLevel(10)))
#
#     def ctrl_relay(self, rel: str, ctrl: bool) -> None:
#         """
#         Функция для воздействия на конкретное реле
#         :param rel: str сокращенное название реле
#         :param ctrl: bool состояние в которое должен переключится
#         :return: None
#         """
#         kl = self.dic_relay[f'{rel}']
#         self.opc.write((kl, ctrl))
#
#     def full_relay_on(self):
#         """
#         Функция включает все реле.
#         """
#         self.opc.write(self.list_relay_true)
#
#     def full_relay_off(self):
#         """
#         Функция отключает все реле.
#         """
#         self.logger.debug("отключение всех реле")
#         self.cli_log.lev_info("отключение всех реле", "gray")
#         self.opc.write(self.list_relay_false)
#         self.logger.debug("все реле отключены")
#         self.cli_log.lev_info("все реле отключены", "gray")
#
#     def perv_obm_tv1_off(self) -> None:
#         self.logger.debug("отключение реле первичной обмотки")
#         self.cli_log.lev_debug("отключение реле первичной обмотки", "gray")
#         self.opc.write(self.list_perv_obm_tv1_off)
#         self.logger.debug("реле первичной обмотки отключены")
#         self.cli_log.lev_debug("реле первичной обмотки отключены", "gray")
#
#     def vtor_obm_tv1_off(self) -> None:
#         self.logger.debug("отключение реле вторичной обмотки")
#         self.cli_log.lev_debug("отключение реле вторичной обмотки", "gray")
#         self.opc.write(self.list_vtor_obm_tv_off)
#         self.logger.debug("реле вторичной обмотки отключены")
#         self.cli_log.lev_debug("реле вторичной обмотки отключены", "gray")
#
#     # def opc_close(self):
#     #     """
#     #     Функция закрывает сессию с OPC сервером.
#     #     """
#     #     self.opc.close('arOPC.arOpcServer.1')
